<h1>Colors</h1>
<div class="headText">
    Click on the Color Name to see how many votes for that color. <br/>
    When you doclick on Total, the sum of above numbers will show
</div>

<table class="votesTable">
    <thead>
        <tr>
            <td>Color</td>
            <td>Votes</td>
        </tr>
    </thead>

    <tbody>
        <?php echo $this->partialLoop('index/partials/color.phtml', $this->colors); ?>
    </tbody>

    <tfoot>
        <tr>
            <td><a href="#" class="totalLink">TOTAL</a></td>
            <td class="td-total"></td>
        </tr>
    </tfoot>
</table>