<h1>Colors</h1>
<div>
    Click on the Color Name to see how many votes for that color. <br/>
    When you doclick on Total, the sum of above numbers will show
</div>

<table class="votesTable">
    <tr>
        <td>Color</td>
        <td>Votes</td>
    </tr>
    <?php echo $this->partialLoop('index/partials/color.phtml', $this->colors); ?>
    <tr>
        <td><a href="#" class="totalLink">TOTAL</a></td>
        <td class="td-total"></td>
    </tr>
</table>