<?php
$this->headTitle('Ошибка');
?>
<?php echo $this->errorpage; ?>


<?php if ('development' === APPLICATION_ENV): ?>


    <h3>Exception information:</h3>
    <p>
        <b>Message:</b>
        <?php if ($this->exception) {
            echo $this->exception->getMessage();
        } ?>
    </p>

    <h3>Stack trace:</h3>
    <pre>
        <?php if ($this->exception) {
            echo $this->exception->getTraceAsString();
        } ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre>
        <?php if ($this->request) {
            echo var_export($this->request->getParams(), true);
        } ?>
    </pre>
<?php endif; ?>
